// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUU-V85Zp8pEABaRfBOpxYBvvn0YATBJs',
    appId: '1:1034667801398:web:29be3ab4bdf23c505a5197',
    messagingSenderId: '1034667801398',
    projectId: 'staging-warrantyhive-16532',
    authDomain: 'staging.moat.app',
    storageBucket: 'staging-warrantyhive-16532.firebasestorage.app',
    measurementId: 'G-3XY3MP8FZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSm2R6RhBBHCbrr3GpjgfGgxiCOxflC0w',
    appId: '1:1034667801398:android:950d0815106f92f75a5197',
    messagingSenderId: '1034667801398',
    projectId: 'staging-warrantyhive-16532',
    storageBucket: 'staging-warrantyhive-16532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlt0sXYCRJ6AqQaubSNxYa6-eIopd9nWs',
    appId: '1:1034667801398:ios:4add1ff94ca396535a5197',
    messagingSenderId: '1034667801398',
    projectId: 'staging-warrantyhive-16532',
    storageBucket: 'staging-warrantyhive-16532.firebasestorage.app',
    iosBundleId: 'com.warrantyhive.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlt0sXYCRJ6AqQaubSNxYa6-eIopd9nWs',
    appId: '1:1034667801398:ios:55a05647806076385a5197',
    messagingSenderId: '1034667801398',
    projectId: 'staging-warrantyhive-16532',
    storageBucket: 'staging-warrantyhive-16532.firebasestorage.app',
    iosBundleId: 'com.warrantyhive.warrantyhive.warrantyhive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUU-V85Zp8pEABaRfBOpxYBvvn0YATBJs',
    appId: '1:1034667801398:web:c22d2ca4a1288c145a5197',
    messagingSenderId: '1034667801398',
    projectId: 'staging-warrantyhive-16532',
    authDomain: 'staging.moat.app',
    storageBucket: 'staging-warrantyhive-16532.firebasestorage.app',
    measurementId: 'G-KZ38G257QT',
  );

}