// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKEBi6W7l4CPDlmjnMFjkE0xZlLSt-lPc',
    appId: '1:12484345459:web:2cf471e895d1baea543406',
    messagingSenderId: '12484345459',
    projectId: 'warrantyhive',
    authDomain: 'go.moat.app',
    storageBucket: 'warrantyhive.appspot.com',
    measurementId: 'G-9VQM1DR2GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDit_WT3gfDIWncYq3vQRvH416eb3Fd5kU',
    appId: '1:12484345459:android:0ca338378d0d9038543406',
    messagingSenderId: '12484345459',
    projectId: 'warrantyhive',
    storageBucket: 'warrantyhive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCqNYYIYZqkm0wxlL0-jG45okdSxqjyts',
    appId: '1:12484345459:ios:26c1e7102786112f543406',
    messagingSenderId: '12484345459',
    projectId: 'warrantyhive',
    storageBucket: 'warrantyhive.appspot.com',
    iosBundleId: 'com.warrantyhive.warrantyhive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCqNYYIYZqkm0wxlL0-jG45okdSxqjyts',
    appId: '1:12484345459:ios:83098f52d80f7c66543406',
    messagingSenderId: '12484345459',
    projectId: 'warrantyhive',
    storageBucket: 'warrantyhive.appspot.com',
    iosBundleId: 'com.warrantyhive.warrantyhive.warrantyhive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKEBi6W7l4CPDlmjnMFjkE0xZlLSt-lPc',
    appId: '1:12484345459:web:f530096edff40759543406',
    messagingSenderId: '12484345459',
    projectId: 'warrantyhive',
    authDomain: 'go.moat.app',
    storageBucket: 'warrantyhive.appspot.com',
    measurementId: 'G-LX7ENNZVV4',
  );

}